language: node_js
sudo: required
node_js:
  - "7"
before_install:
  - git submodule update --init
  - ./tools/wabt/scripts/travis-before-install.sh
  - cd ./tools/wabt/ && make
script: npm test
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
